TRAINING_CLICK_DELAY = 0.01
TRAINING_WAIT_DELAY = 0.2
TRAINING_RETRY_DELAY = 0.15
TRAINING_DETECTION_DELAY = 0.01

RECREATION_MENU_DELAY = 0.5
MENU_RETURN_DELAY = 0.21
MEDIC_CHECK_DELAY = 0.21

ENERGY_READ_RETRY_DELAY = 0.21

RACE_SEARCH_TIMEOUT = 30

MAX_TRAINING_RETRY = 3
MAX_DETECTION_ATTEMPTS = 5
